# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'multimediaUI.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 743)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(398, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 0, 1, 1)
        self.frame_9 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_9.sizePolicy().hasHeightForWidth())
        self.frame_9.setSizePolicy(sizePolicy)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.frame_9)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.label_8 = QtWidgets.QLabel(self.frame_9)
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("../Project Code/icon/picture.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.gridLayout_14.addWidget(self.label_8, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_14.addWidget(self.label_2, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.frame_9, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(398, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 0, 2, 1, 1)
        self.media = QVideoWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(6)
        sizePolicy.setHeightForWidth(self.media.sizePolicy().hasHeightForWidth())
        self.media.setSizePolicy(sizePolicy)
        self.media.setObjectName("media")
        self.gridLayout_3.addWidget(self.media, 1, 0, 1, 3)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.import_PB = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.import_PB.sizePolicy().hasHeightForWidth())
        self.import_PB.setSizePolicy(sizePolicy)
        self.import_PB.setFocusPolicy(QtCore.Qt.NoFocus)
        self.import_PB.setAutoFillBackground(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Project Code/icon/folder-with-up-arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.import_PB.setIcon(icon)
        self.import_PB.setIconSize(QtCore.QSize(32, 32))
        self.import_PB.setObjectName("import_PB")
        self.gridLayout.addWidget(self.import_PB, 0, 0, 1, 1)
        self.export_PB = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.export_PB.sizePolicy().hasHeightForWidth())
        self.export_PB.setSizePolicy(sizePolicy)
        self.export_PB.setFocusPolicy(QtCore.Qt.NoFocus)
        self.export_PB.setAutoFillBackground(True)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../Project Code/icon/save-file-button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.export_PB.setIcon(icon1)
        self.export_PB.setIconSize(QtCore.QSize(32, 32))
        self.export_PB.setObjectName("export_PB")
        self.gridLayout.addWidget(self.export_PB, 0, 1, 1, 1)
        self.frame_8 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_8.sizePolicy().hasHeightForWidth())
        self.frame_8.setSizePolicy(sizePolicy)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setLineWidth(2)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.frame_8)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.playButton = QtWidgets.QPushButton(self.frame_8)
        self.playButton.setEnabled(False)
        font = QtGui.QFont()
        font.setKerning(True)
        self.playButton.setFont(font)
        self.playButton.setFocusPolicy(QtCore.Qt.TabFocus)
        self.playButton.setAutoDefault(False)
        self.playButton.setDefault(False)
        self.playButton.setObjectName("playButton")
        self.gridLayout_16.addWidget(self.playButton, 0, 0, 1, 1)
        self.pauseButton = QtWidgets.QPushButton(self.frame_8)
        self.pauseButton.setEnabled(False)
        self.pauseButton.setObjectName("pauseButton")
        self.gridLayout_16.addWidget(self.pauseButton, 0, 1, 1, 1)
        self.stopButton = QtWidgets.QPushButton(self.frame_8)
        self.stopButton.setEnabled(False)
        self.stopButton.setObjectName("stopButton")
        self.gridLayout_16.addWidget(self.stopButton, 0, 2, 1, 1)
        self.gridLayout.addWidget(self.frame_8, 0, 2, 2, 1)
        self.imagePath_F = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.imagePath_F.sizePolicy().hasHeightForWidth())
        self.imagePath_F.setSizePolicy(sizePolicy)
        self.imagePath_F.setBaseSize(QtCore.QSize(0, 0))
        self.imagePath_F.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.imagePath_F.setFrameShadow(QtWidgets.QFrame.Raised)
        self.imagePath_F.setObjectName("imagePath_F")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.imagePath_F)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_7 = QtWidgets.QLabel(self.imagePath_F)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(16, 16))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("../Project Code/icon/frame-landscape.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.imagePath_F)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 1, 1, 1)
        self.imagePath_LE = QtWidgets.QLineEdit(self.imagePath_F)
        self.imagePath_LE.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(6)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imagePath_LE.sizePolicy().hasHeightForWidth())
        self.imagePath_LE.setSizePolicy(sizePolicy)
        self.imagePath_LE.setObjectName("imagePath_LE")
        self.gridLayout_2.addWidget(self.imagePath_LE, 0, 2, 1, 1)
        self.toolButton = QtWidgets.QToolButton(self.imagePath_F)
        self.toolButton.setObjectName("toolButton")
        self.gridLayout_2.addWidget(self.toolButton, 0, 3, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.imagePath_F, 1, 0, 1, 2)
        self.gridLayout_3.addWidget(self.frame, 2, 0, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 22))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.menuMenu.addAction(self.actionOpen)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Media"))
        self.import_PB.setText(_translate("MainWindow", "Import"))
        self.export_PB.setText(_translate("MainWindow", "Export"))
        self.playButton.setText(_translate("MainWindow", "Play"))
        self.pauseButton.setText(_translate("MainWindow", "Pause"))
        self.stopButton.setText(_translate("MainWindow", "Stop"))
        self.label.setText(_translate("MainWindow", "Path:"))
        self.toolButton.setText(_translate("MainWindow", "..."))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
from PyQt5.QtMultimediaWidgets import QVideoWidget
